services:
  dev-portfolio:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-portfolio
    ports:
      - "3017:3000"
    volumes:
      - .:/app
      - /app/node_modules